# Generated by Django 6.0.5 on 2026-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_declenchement', models.DateTimeField(verbose_name='Déclenché le')),
                ('timestamp_cloture', models.DateTimeField(blank=True, null=True, verbose_name='Clôturé le')),
                ('niveau', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critique', 'Critique')], max_length=16, verbose_name='Niveau de gravité')),
                ('type_alerte', models.CharField(choices=[('seuil', 'Dépassement de seuil'), ('derive', 'Dérive statistique'), ('communication', 'Perte de communication'), ('batterie', 'Batterie faible')], max_length=32, verbose_name="Type d'alerte")),
                ('valeur_declenchante', models.FloatField(blank=True, null=True, verbose_name='Valeur déclenchante')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('acquittee', 'Acquittée'), ('fermee', 'Fermée')], default='ouverte', max_length=16, verbose_name='Statut')),
                ('acquittement_at', models.DateTimeField(blank=True, null=True, verbose_name='Acquitté le')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire technicien')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-timestamp_declenchement'],
            },
        ),
    ]
