# Generated by Django 6.0.5 on 2026-05-25 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='acquittement_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_acquittees', to=settings.AUTH_USER_MODEL, verbose_name='Acquitté par'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='capteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='core.capteur', verbose_name='Capteur concerné'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='seuil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='core.seuil', verbose_name='Seuil franchi'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['capteur', 'statut'], name='idx_alerte_capteur_statut'),
        ),
        migrations.AddIndex(
            model_name='alerte',
            index=models.Index(fields=['-timestamp_declenchement'], name='idx_alerte_ts_desc'),
        ),
    ]
