# Generated by Django 6.0.5 on 2026-05-25 08:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128, unique=True, verbose_name='Nom du site')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude WGS84')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude WGS84')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse postale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('temperature', 'Température'), ('pression', 'Pression'), ('vibration', 'Vibration'), ('qualite_air', "Qualité de l'air")], max_length=32, unique=True, verbose_name='Code technique')),
                ('libelle', models.CharField(help_text="Nom en français pour l'interface utilisateur", max_length=128, verbose_name='Libellé affiché')),
                ('unite_si', models.CharField(help_text='Ex : °C, Pa, m/s², ppm', max_length=16, verbose_name='Unité SI')),
                ('plage_min', models.FloatField(blank=True, null=True, verbose_name='Plage min technique')),
                ('plage_max', models.FloatField(blank=True, null=True, verbose_name='Plage max technique')),
            ],
            options={
                'verbose_name': 'Type de capteur',
                'verbose_name_plural': 'Types de capteurs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='Identifiant unique utilisé dans les topics MQTT (ex : TEMP-001)', max_length=64, unique=True, verbose_name='Identifiant MQTT')),
                ('nom', models.CharField(max_length=128, verbose_name='Nom lisible')),
                ('actif', models.BooleanField(default=True, verbose_name='Capteur actif')),
                ('config_json', models.JSONField(default=dict, help_text='Paramètres opérationnels du capteur (fréquence, modes sleep...)', verbose_name='Configuration JSON')),
                ('firmware_version', models.CharField(blank=True, help_text='Version annoncée par le capteur dans ses messages MQTT', max_length=32, null=True, verbose_name='Version firmware')),
                ('date_installation', models.DateField(blank=True, null=True, verbose_name="Date d'installation")),
                ('date_derniere_calibration', models.DateTimeField(blank=True, null=True, verbose_name='Dernière calibration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='capteurs', to='core.site', verbose_name="Site d'installation")),
                ('type_capteur', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='capteurs', to='core.typecapteur', verbose_name='Type de capteur')),
            ],
            options={
                'verbose_name': 'Capteur',
                'verbose_name_plural': 'Capteurs',
                'ordering': ['identifiant'],
            },
        ),
        migrations.CreateModel(
            name='Seuil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seuil', models.CharField(choices=[('bas_critique', 'Bas critique'), ('bas_warning', 'Bas warning'), ('haut_warning', 'Haut warning'), ('haut_critique', 'Haut critique')], max_length=16, verbose_name='Type de seuil')),
                ('valeur', models.FloatField(help_text="Exprimée dans l'unité SI du type de capteur", verbose_name='Valeur du seuil')),
                ('actif', models.BooleanField(default=True, help_text='Permet de désactiver temporairement un seuil sans le supprimer', verbose_name='Seuil actif')),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seuils', to='core.capteur', verbose_name='Capteur associé')),
            ],
            options={
                'verbose_name': 'Seuil',
                'verbose_name_plural': 'Seuils',
                'ordering': ['capteur', 'type_seuil'],
                'constraints': [models.UniqueConstraint(fields=('capteur', 'type_seuil'), name='seuil_unique_par_capteur_et_type')],
            },
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['site', 'actif'], name='idx_capteur_site_actif'),
        ),
        migrations.AddIndex(
            model_name='capteur',
            index=models.Index(fields=['type_capteur'], name='idx_capteur_type'),
        ),
    ]
