# Generated by Django 6.0.5 on 2026-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='config_json',
            field=models.JSONField(blank=True, default=dict, help_text='Paramètres opérationnels du capteur (fréquence, modes sleep...)', verbose_name='Configuration JSON'),
        ),
    ]
