# Generated by Django 6.0.5 on 2026-05-25 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Horodatage de la mesure')),
                ('valeur', models.FloatField(verbose_name='Valeur mesurée')),
                ('qualite', models.FloatField(default=1.0, help_text='Score de fiabilité fourni par le capteur [0.0 – 1.0]', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Qualité de mesure')),
                ('anomalie_score', models.FloatField(blank=True, help_text='Sortie du modèle TFLite [0.0 – 1.0], null si pas de modèle actif', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name="Score d'anomalie ML")),
                ('meta_json', models.JSONField(default=dict, help_text='Ex : {"batterie": 87, "rssi": -65, "firmware": "1.2.0"}', verbose_name='Métadonnées JSON')),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='core.capteur', verbose_name='Capteur source')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['capteur', '-timestamp'], name='idx_mesure_capteur_ts')],
            },
        ),
    ]
