# Generated by Django 6.0.5 on 2026-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='meta_json',
            field=models.JSONField(blank=True, default=dict, help_text='Ex : {"batterie": 87, "rssi": -65, "firmware": "1.2.0"}', verbose_name='Métadonnées JSON'),
        ),
    ]
