# Generated by Django 6.0.5 on 2026-05-25 08:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom logique, ex : anomalie_temperature', max_length=128, verbose_name='Nom du modèle')),
                ('version', models.CharField(help_text='Convention semver, ex : 1.0.3', max_length=32, verbose_name='Version')),
                ('fichier_tflite', models.FileField(upload_to='modeles_ml/', verbose_name='Fichier .tflite')),
                ('taille_octets', models.IntegerField(help_text='Doit rester < 100 KB (102 400 octets) pour tenir sur les microcontrôleurs', validators=[django.core.validators.MaxValueValidator(102400)], verbose_name='Taille (octets)')),
                ('metriques_json', models.JSONField(default=dict, help_text='Ex : {"accuracy": 0.97, "precision": 0.95, "recall": 0.93, "f1": 0.94}', verbose_name="Métriques d'évaluation")),
                ('actif', models.BooleanField(default=False, help_text="Seul le modèle actif est utilisé pour l'inférence en temps réel", verbose_name='Modèle actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Modèle ML',
                'verbose_name_plural': 'Modèles ML',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeriveDetectee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name="Moment de l'analyse")),
                ('score', models.FloatField(help_text='Écart normé à la moyenne glissante (plus élevé = comportement plus anormal)', verbose_name='Score de dérive')),
                ('moyenne_ref', models.FloatField(help_text="Moyenne calculée sur la fenêtre d'analyse (même unité que les mesures)", verbose_name='Moyenne de référence')),
                ('ecart_type_ref', models.FloatField(help_text="Écart-type calculé sur la fenêtre d'analyse", verbose_name='Écart-type de référence')),
                ('fenetre_heures', models.IntegerField(default=24, help_text="Nombre d'heures sur lesquelles la dérive a été calculée", verbose_name='Taille de fenêtre (heures)')),
                ('alerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derives', to='alertes.alerte', verbose_name='Alerte levée')),
            ],
            options={
                'verbose_name': 'Dérive détectée',
                'verbose_name_plural': 'Dérives détectées',
                'ordering': ['-timestamp'],
            },
        ),
    ]
