# Generated by Django 6.0.5 on 2026-05-25 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedetectee',
            name='capteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derives', to='core.capteur', verbose_name='Capteur analysé'),
        ),
        migrations.AddField(
            model_name='modeleml',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_ml', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddIndex(
            model_name='derivedetectee',
            index=models.Index(fields=['capteur', '-timestamp'], name='idx_derive_capteur_ts'),
        ),
        migrations.AddConstraint(
            model_name='modeleml',
            constraint=models.UniqueConstraint(fields=('nom', 'version'), name='modeleml_unique_par_nom_version'),
        ),
    ]
