# Generated by Django 6.0.5 on 2026-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeleml',
            name='metriques_json',
            field=models.JSONField(blank=True, default=dict, help_text='Ex : {"accuracy": 0.97, "precision": 0.95, "recall": 0.93, "f1": 0.94}', verbose_name="Métriques d'évaluation"),
        ),
    ]
